on:

  push:
    branches:
       - '*'

  pull_request:
    branches: 
       - '*'

  workflow_dispatch:

jobs:

  pytest:
    name: Code Testing
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install packages from requirements.txt
        run: pip install pytest
      - name: Run Pytest
        run: pytest

  pylint:
    name: Python Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: pip install pylint
      - name: Run Pylint
        run: pylint --fail-under=8 .
