on:

  push:
    branches:
       - '*'

  pull_request:
    branches: 
       - '*'

  workflow_dispatch:

jobs:

  pylint:
    name: Code Testing & Quality Check
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Dependencies
        run: |
          pip install -r pipeline/requirements.txt
          pip3 install pytest pylint
      - name: Run Pylint
        run: pylint --fail-under=8 pipeline/*.py
      - name: Run Pytest
        run: pytest pipeline/*.py
